name: forcing-Fe-sedflux
channels:
- conda-forge
- defaults
dependencies:
- bokeh==1.4.0
- bottleneck
- cartopy
- cf_units
- cftime=1.0.3.4
- cmocean
- dask
- distributed
- dask-jobqueue
- dask-mpi
- esmpy
- intake
- intake-esm
- ipywidgets
- jupyter_contrib_nbextensions
- jupyterlab
- matplotlib
- ncar-jobqueue
- nc-time-axis
- netcdf4
- numba
- numpy
- pandas
- pint
- pip
- pop-tools
- pytest
- python=3.7
- scipy
- seaborn
- seawater
- statsmodels
- tabulate
- toolz
- tqdm
- watermark
- xarray
- xesmf=0.1.1
- xgcm
- xhistogram
- xrft
- zarr
- pip:
  - papermill
